# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddstudent():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addstudent(self):
    self.driver.get("http://localhost/stud-attend/index.php")
    self.driver.set_window_size(1186, 800)
    self.driver.find_element(By.ID, "input1").click()
    self.driver.find_element(By.ID, "input1").send_keys("admin")
    self.driver.find_element(By.NAME, "pass").click()
    self.driver.find_element(By.NAME, "pass").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(3) > #optionsRadios1").click()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.ID, "input1").click()
    self.driver.find_element(By.ID, "input1").send_keys("901")
    self.driver.find_element(By.NAME, "st_name").click()
    self.driver.find_element(By.NAME, "st_name").send_keys("yoyo")
    self.driver.find_element(By.NAME, "st_dept").click()
    self.driver.find_element(By.NAME, "st_dept").send_keys("CSE")
    self.driver.find_element(By.NAME, "st_batch").click()
    self.driver.find_element(By.NAME, "st_batch").send_keys("24")
    self.driver.find_element(By.NAME, "st_sem").click()
    self.driver.find_element(By.NAME, "st_sem").send_keys("fall")
    self.driver.find_element(By.NAME, "st_email").click()
    self.driver.find_element(By.NAME, "st_email").send_keys("samir@gmail.com")
    self.driver.find_element(By.NAME, "std").click()
    self.driver.close()
  
